/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.templetower;

import java.util.List;
import java.util.logging.Logger;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;
import it.unibo.templetower.controller.GameDataManagerImpl;
import it.unibo.templetower.model.EnemyRoom;
import it.unibo.templetower.model.FloorData;
import it.unibo.templetower.model.SpawnManagerImpl;
import it.unibo.templetower.model.Trap;
import it.unibo.templetower.util.FloorPrinterUtil;


class AppTest {
    private static final Logger LOGGER = Logger.getLogger(AppTest.class.getName());
    private static final int MAX_FLOORS = 20;

    @Test 
    void testAppHasAGreeting() throws ClassNotFoundException {
        assertNotNull(Class.forName("javafx.scene.Scene"));
    }

    @Test
    void testVerifyPath() {
        final GameDataManagerImpl gameDataManager = new GameDataManagerImpl();
        final String testPath = "tower/floors/floors-data.json";
        assertTrue(gameDataManager.verifyPath(testPath, MAX_FLOORS));
    }

    /**
     * Tests the loading and printing of floor data from the game configuration.
     * This test verifies that:
     * 1. The GameDataManager can successfully load floor data
     * 2. The loaded data contains at least one floor
     * 3. Prints the content of each floor to the console for verification
     */
    @Test
    void testLoadAndPrintFloorData() {
        final GameDataManagerImpl gameDataManager = new GameDataManagerImpl();
        final String testPath = "tower/floors/floors-data.json";
        // Load the game data
        gameDataManager.loadGameData(testPath);
        // Get the floors list
        final List<FloorData> floors = gameDataManager.getFloors();
        // Verify that floors were loaded
        assertFalse(floors.isEmpty(), "Floor list should not be empty");
        // Print floor data
        FloorPrinterUtil.printFloorDetails(floors);
    }

    @Test
    void testSpawnManager() {
        final int level = 1;
        // Load game data
        final GameDataManagerImpl gameDataManager = new GameDataManagerImpl();
        final String testPath = "tower/floors/floors-data.json";
        gameDataManager.loadGameData(testPath);
        final var floors = gameDataManager.getFloors();
        // Instantiate SpawnManagerImpl with loaded floor data
        final SpawnManagerImpl spawnManager = new SpawnManagerImpl(floors);
        final var generatedFloor = spawnManager.spawnFloor(level);
        // Print generated floor details
        LOGGER.info("\n=== Dettagli del Piano Generato ===");
        LOGGER.info("Nome Piano: " + generatedFloor.floorName());
        LOGGER.info("Sprite: " + generatedFloor.spritePath());
        LOGGER.info("Visibilità: " + generatedFloor.visibility());
        LOGGER.info("\nStanze:");
        generatedFloor.rooms().forEach(room -> {
            LOGGER.info("- Stanza " + room.getId() + ": " 
                + (room.getBehavior() == null ? "Vuota" : room.getBehavior().getClass().getSimpleName()));
            if (room.getBehavior() instanceof EnemyRoom) {
                final EnemyRoom er = (EnemyRoom) room.getBehavior();
                LOGGER.info("  [EnemyRoom] Nome enemy: " + er.getName());
                LOGGER.info("  [EnemyRoom] Danno Attacco: " + er.getAttackDamage());
                LOGGER.info("  [EnemyRoom] Punti Vita: " + er.getLifePoints());
            } else if (room.getBehavior() instanceof Trap) {
                final Trap trap = (Trap) room.getBehavior();
                LOGGER.info("  [Trap] Danno: " + trap.getDamage());
            }
        });
        LOGGER.info("=== Fine Dettagli ===\n");
    }

}
